language: objective-c
xcode_project: LSKRoundedProgressView.xcodeproj
xcode_scheme: LSKRoundedProgressView

before_install:
    - brew update
    - brew upgrade xctool
    - xctool -v

script:
    - pod lib lint
    - xctool -project LSKRoundedProgressView.xcodeproj -sdk iphonesimulator -scheme LSKRoundedProgressView build
    - xctool -project LSKRoundedProgressView.xcodeproj -sdk iphonesimulator -scheme LSKRoundedProgressView test
